### ISSUE TITLE
Недоработки слайдера

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/SliderPlugin#26]
Слайдер должен быть реализован следующим образом

У слайдера должен быть шаг в виде конкретного значения, а не в процентах или пикселях. Например я хочу слайдер от 0 до 100 с шагом 5 - это значит меня интересуют значения от 0 до 100 кратные 5 (остальные не интересуют). Округление тут то же не имеет смысла.

**Comment by Rqik** [comment]
1. Добавил возможность указывать размер шага в числах
2. Переписал на класс функции для демо страницы
3. Обработчики событий вынес в отдельные методы
Нашел 2 ошибки. Перестала работать передача параметров при инициализации и нет методов для touch событий

**Comment by Rqik** [comment]
Исправил ошибки  и баги которые нашел.
Шаг слайдера теперь работает корректно.

**Comment by mglknFSD** [comment]
В Firefox слайдер не работает.

https://user-images.githubusercontent.com/75975369/115956056-5f763780-a503-11eb-9d53-04b256dd97c7.mp4

**Comment by mglknFSD** [comment]
Убери, пожалуйста шаг в процентах - я не понимаю зачем он нужен.

**Comment by mglknFSD** [comment]
"округление после запятой" - это тоже не нужный параметр.

**Comment by mglknFSD** [comment]
Немного багов слайдера

https://user-images.githubusercontent.com/75975369/115956489-b2e98500-a505-11eb-86fc-dae6f91eea57.mp4


https://user-images.githubusercontent.com/75975369/115956490-b41ab200-a505-11eb-9a18-fb3d6ea9be91.mp4


https://user-images.githubusercontent.com/75975369/115956491-b41ab200-a505-11eb-9b74-fb632cd8657c.mp4

**Comment by Rqik** [comment]
Исправил.
В Firefox теперь работает исправно. 
В Model добавил доп функционал чтобы данные обрабатывались корректно.
Починил тесты

**Comment by mglknFSD** [comment]
Еще несколько багов. (снимал в Firefox, не знаю проявляется ли это все в Chrome)


https://user-images.githubusercontent.com/75975369/116789968-9c6d9b80-aaba-11eb-96dc-64625209760e.mp4


https://user-images.githubusercontent.com/75975369/116789969-9d063200-aaba-11eb-99f1-dcb2d2ac9cee.mp4


https://user-images.githubusercontent.com/75975369/116789970-9d9ec880-aaba-11eb-98ef-494550aed300.mp4


https://user-images.githubusercontent.com/75975369/116789971-9e375f00-aaba-11eb-9f5c-00f4a8cfdf57.mp4
