### ISSUE TITLE
ts

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/SliderPlugin#33]
Вложеных if лучше избегать. Такой код тяжело читать и модифицировать. Всегда можно переписать на более "плоскую" структуру кода. 

![nested if](https://user-images.githubusercontent.com/75975369/117543595-3044e780-b026-11eb-869c-2ea134336bda.jpg)

**Comment by mglknFSD** [comment]
Не очень понятные имена у переменных. Я не смог понять что такое `res`

![naming](https://user-images.githubusercontent.com/75975369/117543608-3fc43080-b026-11eb-9ee0-b16e0102811f.jpg)

**Comment by mglknFSD** [comment]
Следует избегать циклов for. Они хуже читаются чем map/forEach

![for](https://user-images.githubusercontent.com/75975369/117543724-afd2b680-b026-11eb-84ac-cdff000ce7ae.jpg)

**Comment by mglknFSD** [comment]
Мертвая переменная.

![not used var](https://user-images.githubusercontent.com/75975369/117544055-2f14ba00-b028-11eb-9ef4-9ea68ab34f68.jpg)

**Comment by mglknFSD** [comment]
Следует избегать неявного приведения типов. 

![приведение типов](https://user-images.githubusercontent.com/75975369/117544112-77cc7300-b028-11eb-95a1-e580ecd691f0.jpg)

**Comment by Rqik** [comment]
Убрал вложенность ( вынес в отдельный метод проверку), удалил неиспользуемый элемент, убрал неявные преобразования типов Number

**Comment by Rqik** [comment]
> Следует избегать циклов for. Они хуже читаются чем map/forEach
> 
> ![for](https://user-images.githubusercontent.com/75975369/117543724-afd2b680-b026-11eb-84ac-cdff000ce7ae.jpg)

Мне самому больше нравятся map и forEach, но тут у меня метод принимает число и отрисовывает интервалы. Создавать отдельно пустой массив, чтобы потом пройтись по пустым элементам и заполнить их. Как по мне ненужное усложнение в данном случае. 
Переименовал метод возможно название вас сбило

**Comment by mglknFSD** [comment]
> 
> 
> > Следует избегать циклов for. Они хуже читаются чем map/forEach
> > ![for](https://user-images.githubusercontent.com/75975369/117543724-afd2b680-b026-11eb-84ac-cdff000ce7ae.jpg)
> 
> Мне самому больше нравятся map и forEach, но тут у меня метод принимает число и отрисовывает интервалы. Создавать отдельно пустой массив, чтобы потом пройтись по пустым элементам и заполнить их. Как по мне ненужное усложнение в данном случае.
> Переименовал метод, возможно название вас сбило

Тут нет никакого усложнения. В функциональных языках так и делают, и некоторые языки смешанной парадигмы то же перенимают эту практику. Например в python в стандартной библиотеке есть функции range и xrange
